dunst -config $HOME/.config/dunst/dunstrc &
flameshot &
udiskie &
xautolock -time 3 -locker "slock -m \"Locked at $(date +'%I:%M %p')\"" &
xcompmgr &
xwallpaper --maximize $HOME/pictures/wallpapers/wp
signal-desktop --start-in-tray &
clipmenud &
sxhkd &
nm-applet &
dwmblocks &
exec dwm
