#!/bin/sh

# Bash prompt variables
prompt_start='%B%F{9}[%f%b'
prompt_end='%B%F{9}]%f%b'
username='%B%F{130}%n%f%b'
hostname='%B%F{130}%m%f%b'
cwd='%B%F{82}%~%f%b'
prompt_symbol='%B%#%b'
at='%F{131}@%f'
arrow='%B%F{9}>%f%b'

# Prompt colors
col_1='%F{130}'
col_2='%B%F{131}'
col_3='%B%F{9}'
col_4='%B%F{82}'
yellow='\[\e[1;33m\]'
cyan='\[\e[1;36m\]'
green='\[\e[1;32m\]'
purple='\[\e[01;34m\]'
col_end='%f'

autoload -Uz vcs_info
zstyle ':vcs_info:git:*' formats ' (%b)'
precmd() { vcs_info }
setopt prompt_subst

PS1='$username$at$hostname $cwd${vcs_info_msg_0_} $arrow '
