#!/bin/sh

alias \
    cp="cp -iv" \
    dotfiles="/usr/bin/git --git-dir=$HOME/Documents/repos/dotfiles --work-tree=$HOME" \
    email="neomutt" \
    irssi="irssi --config=$HOME/.config/irssi/config" \
    ls="exa -l --group-directories-first --color=auto --group" \
    mkdir="mkdir -pv" \
    mv="mv -iv" \
    neomutt="cj-mail; neomutt; cj-mail; pkill -RTMIN+2 i3blocks" \
    newsboat="newsboat; pkill -RTMIN+11 i3blocks" \
    ovim="nvim \$(fzf -e)" \
    rm="rm -vI" \
    um="udiskie-mount" \
    uu="udiskie-umount" \
    v="nvim" \
    vea=". venv/bin/activate" \
    ved="deactivate" \
    wget="wget --hsts-file=$XDG_CACHE_HOME/wget-hsts" 
