#!/bin/sh

# Bash prompt variables
prompt_start='['
prompt_end=']'
username='\u'
hostname='\h'
cwd='\w'
prompt_symbol='\$'

# Prompt colors
col_1='\[\e[1;38;5;130m\]'
col_2='\[\e[1;38;5;181m\]'
col_3='\[\e[1;38;5;160m\]'
col_4='\[\e[1;38;5;46m\]'
yellow='\[\e[1;33m\]'
cyan='\[\e[1;36m\]'
green='\[\e[1;32m\]'
purple='\[\e[01;34m\]'
col_end='\[\e[0m\]'

git_data() {
    if [ -d .git ]
    then
        git status 2> /dev/null | grep "working tree clean" &> /dev/null
        if [ $? -ne 0 ]; then STATUS="!"; else STATUS=""; fi
        echo -n " (`git branch 2>/dev/null | grep '^*' | colrm 1 2`$STATUS)"
    fi
}

PS1="$col_3$prompt_start$col_end $col_1$username$col_end$col_2@$col_end$col_1$hostname$col_end $col_4$cwd$col_end$purple\$(git_data)$col_end $col_3$prompt_end$col_end$prompt_symbol "
