#!/bin/sh

# basic shell commands 
alias \
    cp="cp -iv" \
    mkdir="mkdir -pv" \
    mv="mv -iv" \
    ls="exa -l --group-directories-first --color=auto --group" \
    rm="rm -vI"

# python virtual environment
alias \
    vea=". venv/bin/activate" \
    ved="deactivate" \
    wget="wget --hsts-file=$XDG_CACHE_HOME/wget-hsts" 

# others
alias \
    cr="cd $HOME/documents/repos" \
    irssi="irssi --config=$HOME/.config/irssi/config"  \
    news="newsboat"
