#!/bin/sh

# Default applications
export \
    BROWSER=firefox \
    EDITOR=nvim \
    TERMINAL=alacritty

    
# Paths
export \
    PATH=$HOME/.local/bin:$HOME/.local/bin/scripts:$HOME/.local/bin/statusbar:$HOME/.local/bin/cronjobs:$HOME/.local/bin/applications:$PATH:$HOME/.local/bin/node/bin \
    XAUTHORITY=$XDG_RUNTIME_DIR/Xauthority \
    XINITRC=$XDG_CONFIG_HOME/x11/xinitrc \
    XDG_DATA_HOME=$HOME/.local/share


# ZSH
export \
    ZDOTDIR=$XDG_CONFIG_HOME/zsh


# Others
export \
    ANSIBLE_LIBRARY=$XDG_CONFIG_HOME/ansible \
    CALIBRE_USE_DARK_PALETTE=1 \
    CARGO_HOME=$XDG_CONFIG_HOME/cargo \
    LESSHISTFILE=- \
    TERMINFO=$XDG_DATA_HOME/terminfo \
    TERMINFO_DIRS=$XDG_DATA_HOME/terminfo:/usr/share/terminfo \
