dunst -config $HOME/.config/dunst/dunstrc &
flameshot &
udiskie &
xautolock -time 3 -locker slock -m \"Locked at $(date +'%I:%M %p')\" &
xcompmgr &
check-hostname
set-bg
signal-desktop --start-in-tray &
clipmenud &
sxhkd &
dwmblocks &
exec dwm
