dunst -config $HOME/.config/dunst/dunstrc &
flameshot &
udiskie &
xautolock -time 3 -locker slock &
xcompmgr &
xrdb $HOME/.Xresources &
check-hostname
setxkbmap -option 'grp:alt_shift_toggle'
set-bg
dwmblocks &
exec dwm
